### ISSUE TITLE
Read-only mode when public, full-featured when private

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/cesium_ynh#19]
Bonjour,

Je me demandais, suite à cette nouvelle, https://forum.monnaie-libre.fr/t/cesium-evolue-aie-ca-va-piquer-mais/10015 , si l'application Cesium sur Yunohost va être abandonné?

@+

Thatoo

**Comment by M5oul** [comment]
I think it is no an issue to use the app and sign Duniter documents (transactions, certifications, …) with our private keys for a private usage behind the SSO as we can trust the distribution with this application.

To improve the security, the package could verify the checksum which is now provided by the upstream project.

The application is now installed [as private by default](https://github.com/YunoHost-Apps/cesium_ynh/commit/7e87676c83d5f53cdd4032f67874b70fb9dd672c).

I suggest to set-up following modes to be consistent with the upstream decision:
- private - full-featured
- public - read-only

**Comment by rodinux** [comment]
Oh, I don't know why, but I finally could remove a version with public mode and read-only and install a private mode which is only accessible with SSO connection !

**Comment by lapineige** [comment]
If we can use it behind the SSO, do we need a read-only mode ? There will not be a security issue as for public instances.

**Comment by rodinux** [comment]
By default is a private mode behind the SSO. But it still have this line in the intall script 
```ynh_app_setting_set "$app" is_public "$is_public"
```
