### ISSUE TITLE
Connexion au nœud via https

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/cesium_ynh#2]
Lorsqu'on actualise la page "Monnaie" on obtient l'erreur suivante : 
"Échec de la récupération des règles de la monnaie"

**Comment by M5oul** [comment]
Je rencontre un bug semblable :
![capture du 2016-06-14 13-25-00](https://cloud.githubusercontent.com/assets/4758871/16041004/75fd9a36-3233-11e6-93e3-a6e855432a49.png)

**Comment by blavenie** [comment]
A voir, mais à mon avis vous avez un problème de restriction d'accès, qui n'est pas du à Cesium...
Pouvez-vous essayé de débugger ?

**Comment by M5oul** [comment]
Dans ma console web j’ai ce message d’erreur :
```fish
Chargement du contenu mixte actif « http://cgeek.fr:9330/blockchain/parameters » (non sécurisé) sur une page sécurisée[En savoir plus] cesium-18deee1445.js:13:8768
Error: The operation is insecure.
r/c/<.on@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:41:20993
CurrencyViewController/e.startListeningOnSocket@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:1:15500
CurrencyViewController/e.load@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:1:15327
CurrencyViewController/</<@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:1:15161
s@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:23377
c/<@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:23549
En/this.$get</p.prototype.$eval@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:31062
En/this.$get</p.prototype.$digest@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:29566
En/this.$get</p.prototype.$apply@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:31347
a@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:6192
v@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:8042
Mt/</w.onload@https://ynh.local/cesium/dist_js/cesium-18deee1445.js:13:8585
 cesium-18deee1445.js:13:16312

>>>>>>> DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: https://ynh.local/cesium/dist_js/cesium-18deee1445.js:41]
```

**Comment by vincentux** [comment]
Comment avoir les logs de l'appli ?

**Comment by M5oul** [comment]
Avec `F12` sous Firefox.

**Comment by vincentux** [comment]
ok voici mon résultat : 
![bug_02_cesium](https://cloud.githubusercontent.com/assets/11737560/16042221/032ddbcc-323a-11e6-8f48-27ae5bd8d252.png)

**Comment by M5oul** [comment]
Ces deux problèmes viennent du fait que Césium est accédé via HTTPS, ce qui n’est pas le cas pour les nœuds.

- [Plus d’informations](https://support.mozilla.org/fr/kb/blocage-du-contenu-mixte-avec-firefox)

**Comment by blavenie** [comment]
ok donc vous avez la solution (dans le lien indiqué par @M5oul : on peut désactiver cette contrainte de sécurité)

**Comment by blavenie** [comment]
ou alors, est-ce que par défaut Cesium n'accéderait pas au noeud local Duniter (aussi sous YunoHost) qui cette fois serait ten https ?

**Comment by M5oul** [comment]
Je n’ai pas réussit à désactiver la contrainte de sécurité dans Firefox 47.

Par contre, se connecter au nœud local en HTTPS me semble une bonne voie à suivre.

**Comment by M5oul** [comment]
Linked to https://github.com/duniter/cesium/issues/65.

**Comment by M5oul** [comment]
To summarize, many functionalities of Cesium are broken because Firefox want all requests to be done via HTTPS.
As cesium app is requests via HTTPS, requests to nodes must also be done via HTTPS.
Modifiying the config file to the local node don't correct the problem.
To solve this issue, requestst to local node must be done via:
- [localhost](https://github.com/duniter/duniter/issues/481)
- an URL using https.

**Comment by M5oul** [comment]
Seems fixed upstream!
Or because default endpoint is using https.
