### ISSUE TITLE
Mise à jour du dépôt

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/cesium_ynh#6]
Salut @M5oul 
c'est abusé de te demander aussi de faire les modifs ici pour installer la dernière version de Césium.
Le nouveau dépôt : https://git.duniter.org/clients/cesium/cesium

Merci ;)

**Comment by M5oul** [comment]
Je ne maintiens plus cette app.
Pourquoi n’installes-tu pas Césium avec en tant qu’extension de l’app Duniter ?

**Comment by vincentux** [comment]
Comme un module, tu veux dire ?

**Comment by M5oul** [comment]
Oui, exactement.

**Comment by M5oul** [comment]
The application is still retrieving last unstable release from GitHub.
As upstream project is still publishing bundles on GitHub and not on GitLab, let’s keep things like that.
